#!/usr/bin/env bash

SCRIPT_DIRECTORY=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

VERBOSE="false"
VERBOSE_ALL="false"
while getopts "vV" OPTION; do
  case "$OPTION" in
    v) VERBOSE="true";;
    V) VERBOSE_ALL="true";;
  esac
done
shift "$((OPTIND-1))"

git -C "$SCRIPT_DIRECTORY" submodule update --init --recursive --remote

if [[ "$VERBOSE_ALL" == "true" ]]; then
  "$SCRIPT_DIRECTORY/base-image/build-image" -V
else
  "$SCRIPT_DIRECTORY/base-image/build-image"
fi

if [[ "$VERBOSE" == "true" || "$VERBOSE_ALL" == "true" ]]; then
    printf '\nBuilding: "ubuntu-emacs"\n\n'

  docker build --file "$SCRIPT_DIRECTORY/Dockerfile" --tag ubuntu-emacs "$SCRIPT_DIRECTORY"
else
  docker build --quiet --file "$SCRIPT_DIRECTORY/Dockerfile" --tag ubuntu-emacs "$SCRIPT_DIRECTORY"
fi
